### ISSUE TITLE
BUG in check_pf_ipsec_tunnel

### ISSUE THREAD

**Issue by ReclusiveGeek** [oneoffdallas/pfsense-nagios-checks#1]
check_pf_ipsec_tunnel is not working with a hostname. 

if I use -e <hostaname> I get "CRITICAL - IPSEC VPN tunnel not found:  <hostname>

if then do a ping to <hostname> and get the IP Address 

I then use -e <ip_address> I get "OK - IPSEC VPN tunnel to ,<p_address>"

Pfsense can resolve it as it can bring up tunnel using the <hostaname> which I have to do as the site does not have a fix IP Addrees.

Thanks for the great article "Monitoring pfSense with Nagios" and the extra plugins I have found them very useful. And yes it does work with Nagios Core if you set up the command and server_object manually.

Many thanks
Paul

**Comment by oneoffdallas** [comment]
Paul, thank you for the kind words and I'm happy to hear the scripts/write-up are helping you. I was able to reproduce the issue you are describing. It appears the "/usr/local/sbin/ipsec statusall" command resolves the hostname to an IP address and then refers to it only by IP address thereafter, which must have changed at some point. Give me a few days and I'll make some changes to correct this. Thanks for the heads up!

**Comment by oneoffdallas** [comment]
Paul, I made several modifications to the check_pf_ipsec_tunnel script. I verified both hostname and IP address are now working as inputs (below). Thanks again for the heads up!

/usr/local/libexec/nagios: ./check_pf_ipsec_tunnel -e myip
OK - IPSEC VPN tunnel to myip - ESTABLISHED 76 minutes ago
/usr/local/libexec/nagios: ./check_pf_ipsec_tunnel -e myip -name test
OK - IPSEC VPN tunnel to test - ESTABLISHED 76 minutes ago
/usr/local/libexec/nagios: ./check_pf_ipsec_tunnel -e myhostname
OK - IPSEC VPN tunnel to myhostname - ESTABLISHED 77 minutes ago
/usr/local/libexec/nagios: ./check_pf_ipsec_tunnel -e myhostname -name test2
OK - IPSEC VPN tunnel to test2 - ESTABLISHED 77 minutes ago

**Comment by ReclusiveGeek** [comment]
Thanks very much will give it a test tomorrow as I am just off to bed.

Paul Jones



-------- Original Message --------
