### ISSUE TITLE
Unable to create user nagios in pfsense

### ISSUE THREAD

**Issue by stevetoza** [oneoffdallas/pfsense-nagios-checks#2]
Hello, 

Im trying to create the user nagios in pfsense but its saying 

That username is reserved by the system.

Wonder if you can help me get this running.
Thanks

**Comment by oneoffdallas** [comment]
Hey Steve! The only time I've seen that error is when you previously installed the NRPE pfSense package. You can either use a different name or remove NRPE. IIRC, you will also need to remove the user manually via the command line as the NRPE package uninstall doesn't remove it for you. Holler if you need anything else!

**Comment by stevetoza** [comment]
Hey

Thanks for the swift reply. I’ve removed the user from /etc/passwd and it’s allowed me to create the user 👍🏻. I’ll continue the rest of the setup later this evening

**Comment by oneoffdallas** [comment]
Excellent! FWIW, I added a note regarding the 'username is reserved' error to the Linux Included guide as well. 
https://www.linuxincluded.com/monitoring-pfsense-with-nagios-xi-using-ssh-part-1/

**Comment by stevetoza** [comment]
Got it working - Have an issue on the Total Processes one 

(No output on stdout) stderr: /bin/sh: 1: cannot open hostname: No such file 

Any ideas - Thanks in advance

**Comment by oneoffdallas** [comment]
Can you run the command below from the pfSense command line? 
/usr/local/libexec/nagios/check_procs -w 200 -c 400 
If that works, then my next step is verifying I can run the full command from the command line of the Nagios box. On Nagios XI, the command is 
check_by_ssh -H $HOSTADDRESS -C "/usr/local/libexec/nagios/check_procs -w 200 -c 400" 
My guess is that there's an issue with the command calls/structure on the Nagios box. This is even more likely true if you are configuring Nagios Core. Also, Have you looked at bottom of part 3 of the guide? It has downloadable versions of the commands.cfg and services.cfg files, which should help quite a bit. Good luck!

**Comment by stevetoza** [comment]
Many thanks I got it working was a typo in my cfg for this one which completely threw me off.

Thanks very much for all the assistance. Much appreciated - Working a treat on Nagios Core :) 👍

**Comment by oneoffdallas** [comment]
That's great to hear! It is one of the first things I do when I install a new pfSense.
