### ISSUE TITLE
check_pf_version causes PHP warning in logs

### ISSUE THREAD

**Issue by oraclesod** [oneoffdallas/pfsense-nagios-checks#4]
I have been seeing the following error in the PHP logs of pfsense:
>/usr/local/libexec/nagios/check_pf_version: WARNING: Could not mark subsystem: pkg dirty

This is because nagios does not have the ability to write to /var/run/pkg.dirty when running get_system_pkg_version()

I fixed this for myself by editing /usr/local/libexec/nagios/check_pf_version
and replacing:

>require_once("pkg-utils.inc");
>$system_pkg_version  = get_system_pkg_version();

With:

>require_once("pkg-utils.inc");
>global $g;
>
>if (file_exists("{$g['varrun_path']}/pkg.dirty")) {
>  $system_pkg_version  = get_system_pkg_version(false,false);
>} else {
>  shell_exec("sudo touch "."{$g['varrun_path']}/pkg.dirty");
>  $system_pkg_version  = get_system_pkg_version(false,false);
>  shell_exec("sudo rm " . "{$g['varrun_path']}/pkg.dirty");
>}

Just posting if someone else is looking for a fix

**Comment by oneoffdallas** [comment]
Thanks for the update @oraclesod! It does indeed remove the PHP error from system.log. Are there any potential side effects to creating and/or removing the file?

**Comment by oraclesod** [comment]
Not too sure about that, although i'm checking if the file exists before running and only creating/removing it if it doesn't exist

To be able to get around this would require bringing in lots of code and not sure it would be worthwhile

**Comment by oneoffdallas** [comment]
Tested on several systems and it works as expected. Thanks again for the recommendation @oraclesod !
