### ISSUE TITLE
pfsense v2.5 / 21.02 problem with check_pf_cpu

### ISSUE THREAD

**Issue by adelphi-company** [oneoffdallas/pfsense-nagios-checks#5]
After Update to pfsense 21.02 the cpu check no longer works:

 /usr/local/libexec/nagios/check_pf_cpu -w 80 -c 95
expr: syntax error
[: -ge: unexpected operator
OK - CPU Usage = %|CPU=;;;;

Any ideas?

**Comment by oneoffdallas** [comment]
I updated the CPU script a few days ago for this very reason. Did you try the latest version in the repo?

**Comment by adelphi-company** [comment]
Perfect, thanks!
