### ISSUE TITLE
Pfsense monitoring Icinga2 - CRITICAL - Plugin timed out after 10 seconds

### ISSUE THREAD

**Issue by hsyedshams** [oneoffdallas/pfsense-nagios-checks#6]
Hi,
Recently added new pfsense system, existing one working as expected.I have installed package nagios-plugins on pfsense for monitoring like existing pfsense.
Existing ssh-keygen -t ed25519 using for new setup added to pfsense.

Installed:
sudo pkg install nagios-plugins
Run command : /usr/local/libexec/nagios/check_procs
PROCS OK: 88 processes | procs=88;;;0

curl -LO https://github.com/oneoffdallas/pfsense-nagios-checks/archive/master.zip
sudo unzip -j master.zip -d /usr/local/libexec/nagios/
sudo chmod +x /usr/local/libexec/nagios/check_pf_*

Installation check:  /usr/local/libexec/nagios/check_pf_version
OK - already at latest version
Current version: 
Built on: Mon Apr 12 07:50:14 EDT 2021

 I am getting error on icinga2 web interface :
**Plugin Output :CRITICAL - Plugin timed out after 10 seconds****
![image](https://user-images.githubusercontent.com/33788501/125202952-609f4100-e276-11eb-9b75-511b659c973f.png)

Could you please help me to solve this issue. The other pfsense is working as expected with same monitoring server.

**Comment by 47k** [comment]
Script is not workin anymore. I have the same issue on my systems/firewalls.  There is something wrong with the Remote version:

**/usr/local/libexec/nagios/check_pf_version**
```
OK - already at latest version
Current version:
Built on: Fri Jul 02 15:33:00 EDT 2021
Remote version:
```

**Comment by oneoffdallas** [comment]
These are running on a lot of systems @47k including several of my own. My guess is that your check is timing out. Try increasing the check to 30 secs or so as I know the remote one takes longer than most others. I also have the version check set to run every 960 mins, otherwise, you will see intermittent timeouts because it is unable to hit the check server.
--
WARNING - new version available
Current version: 21.05.2
Built on: Fri Oct 22 15:21:04 UTC 2021
Remote version: 22.01

**Comment by oneoffdallas** [comment]
My apologies @hsyedshams as I never saw your issue. I'm assuming you have this resolved by now. If not, I would double-check that the passwordless SSH setup is working properly. The easiest way to verify is by running everything from the command line. Basically, run the commands local. If they work, run them using the SSH check from the Nagios/Icinga server. Once those are both working, the only other issue I've ran into is regarding elevated privileges where sudo is not working. Best of luck!
