### ISSUE TITLE
Checks that have issues on pfsense 23.01 RC

### ISSUE THREAD

**Issue by michaellacroix** [oneoffdallas/pfsense-nagios-checks#9]
Hello, I have found two service checks that do not work correctly on the new pfsense distro:
check_pf_version
check_pf_cpu_temp

The CPU temp checks reports an unexpected error. And the version check does not report the remote version from the nagios server. But does work locally on pfsense. Thanks

**Comment by oneoffdallas** [comment]
Hey @michaellacroix! Someone had a similar question on my blog. We have not tested as 23.01 is still a release candidate, however, we will take a look at this soon. In the meantime, if you happen to find the error in the code, please feel free to submit the updates. Thanks!

**Comment by michaellacroix** [comment]
Hi Dallas,

I cannot identify any error in the code. Now that 23.01 is out of RC I am still able to verify the two checks I identified still do not work on this version. If I can help in anyway please let me know.

Thanks,
Mike

**Comment by oneoffdallas** [comment]
Hey @michaellacroix! We upgraded one of our lab firewalls to 23.01 and while it broke one of our peer-to-peer shared key OpenVPN tunnels, all custom Nagios checks including the 2 you mentioned worked without issue (below). What kind of hardware are you running on? If there is a spot for the temp check to fail, I'm guessing it would be in the sysctl command and what's returned. Can you run that from the command line and let us know what you get back? If you look at the check_pf_cpu_temp code, I actually left a little note to myself and others about potential formatting issues.
** CPU TEMP **
[23.01-RELEASE][nagios@pf.labz]/usr/local/libexec/nagios: ./check_pf_cpu_temp -w 30 -c 50
CRITICAL - CPU temperature - 64 (C)|TEMP=64;;;;
** VERSION **
[23.01-RELEASE][nagios@pf.labz]/usr/local/libexec/nagios: sudo /usr/local/libexec/nagios/check_pf_version
OK - already at latest version
Current version: 23.01
Built on: Fri Feb 10 20:06:58 UTC 2023
Remote version: 23.01
** SYSCTL **
[23.01-RELEASE][nagios@pf.labz]/usr/local/libexec/nagios: /sbin/sysctl -a |grep temperature
dev.armada_thermal.0.temperature: 58

**Comment by oneoffdallas** [comment]
I don't know that you use it from the blog/tutorial, but we also found the built-in check_icmp always returns critical. We switched the check to check_ping (similar functionality) and other it being slower, it seems to work without issue. I'll reach out to Nagios who maintains the check_icmp plugin.

**Comment by michaellacroix** [comment]
Thanks for getting back to me.

As soon as I get a chance I will run these checks again. I’m using supermicro hardware. The issues I experience happened after the upgrade, that’s why I kind of assumed that was the issue.

Mike

**Comment by michaellacroix** [comment]
Yep, I had the same thing happen to my and I did the same thing to bypass it.

Thanks,
Mike
